#!/usr/bin/env python3
"""CIDector Orchestrator — automated benchmark → issue → fix → PR loop.

Usage:
    python scripts/orchestrator.py benchmark   # run benchmarks, create issues on failure
    python scripts/orchestrator.py fix         # pick up open issues, claude-fix in worktrees
    python scripts/orchestrator.py loop        # full cycle: benchmark then fix
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import shutil
import subprocess
import sys
import textwrap
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
LOGS_DIR = PROJECT_ROOT / "logs"
WORKTREES_DIR = PROJECT_ROOT / ".worktrees"
BENCHMARK_RUNNER = PROJECT_ROOT / "benchmarks" / "run_benchmarks.py"

ISSUE_LABEL = "claude-fix"
BENCHMARK_LABEL = "benchmark-failure"
CLAUDE_MAX_TURNS = 25
CLAUDE_MAX_BUDGET_USD = 5

_config: dict = {"max_issues": 5}

logger = logging.getLogger("orchestrator")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _setup_logging(verbose: bool) -> None:
    LOGS_DIR.mkdir(parents=True, exist_ok=True)
    date_str = datetime.now().strftime("%Y-%m-%d")
    log_file = LOGS_DIR / f"orchestrator_{date_str}.log"

    file_handler = logging.FileHandler(log_file, encoding="utf-8")
    file_handler.setLevel(logging.DEBUG)
    file_handler.setFormatter(logging.Formatter(
        "%(asctime)s [%(levelname)s] %(message)s", datefmt="%H:%M:%S"
    ))

    console_handler = logging.StreamHandler(sys.stderr)
    console_handler.setLevel(logging.DEBUG if verbose else logging.INFO)
    console_handler.setFormatter(logging.Formatter("%(levelname)s: %(message)s"))

    logger.setLevel(logging.DEBUG)
    logger.addHandler(file_handler)
    logger.addHandler(console_handler)


def _run(cmd: list[str], *, cwd: str | Path | None = None,
         check: bool = True, capture: bool = True) -> subprocess.CompletedProcess:
    """Thin wrapper around subprocess.run with logging."""
    logger.debug("$ %s (cwd=%s)", " ".join(cmd), cwd or ".")
    result = subprocess.run(
        cmd,
        capture_output=capture,
        text=True,
        cwd=cwd,
    )
    if result.returncode != 0:
        logger.debug("stderr: %s", (result.stderr or "").strip()[:500])
    if check and result.returncode != 0:
        raise subprocess.CalledProcessError(
            result.returncode, cmd, result.stdout, result.stderr
        )
    return result


def _gh_available() -> bool:
    try:
        _run(["gh", "auth", "status"], check=False)
        return True
    except FileNotFoundError:
        return False


def _claude_available() -> bool:
    return shutil.which("claude") is not None


def _save_benchmark_report(report: dict) -> Path:
    LOGS_DIR.mkdir(parents=True, exist_ok=True)
    date_str = datetime.now().strftime("%Y-%m-%d")
    path = LOGS_DIR / f"benchmark_{date_str}.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(report, f, ensure_ascii=False, indent=2)
    logger.info("Benchmark report saved to %s", path)
    return path


# ---------------------------------------------------------------------------
# Issue body formatting
# ---------------------------------------------------------------------------

def _format_issue_body(report: dict) -> str:
    """Build a Markdown issue body from a benchmark report."""
    lines: list[str] = []
    lines.append(f"## Benchmark Report — {report.get('timestamp', 'N/A')}")
    lines.append("")
    lines.append(f"**Total**: {report['total']} · "
                 f"**Passed**: {report['passed']} · "
                 f"**Failed**: {report['failed']} · "
                 f"**Skipped**: {report['skipped']}")
    lines.append("")

    failures = [r for r in report["results"] if r["status"] == "FAIL"]
    if failures:
        lines.append("### Failed Cases")
        lines.append("")
        for f in failures:
            lines.append(f"- **{f['name']}**: {f.get('error', 'unknown error')} "
                         f"({f.get('duration_sec', '?')}s)")
        lines.append("")

    lines.append("### All Results")
    lines.append("")
    lines.append("| Case | Status | Duration | Error |")
    lines.append("|------|--------|----------|-------|")
    for r in report["results"]:
        icon = {"PASS": "✅", "FAIL": "❌", "SKIP": "⏭️"}.get(r["status"], "?")
        err = r.get("error", "")
        lines.append(f"| {r['name']} | {icon} {r['status']} | {r.get('duration_sec', '-')}s | {err} |")

    lines.append("")
    lines.append("---")
    lines.append("*Auto-generated by `scripts/orchestrator.py benchmark`*")
    return "\n".join(lines)


def _build_issue_title(report: dict) -> str:
    failed = report["failed"]
    date_str = report.get("timestamp", "")[:10]
    names = [r["name"] for r in report["results"] if r["status"] == "FAIL"]
    summary = ", ".join(names[:3])
    if len(names) > 3:
        summary += f" +{len(names) - 3} more"
    return f"[Benchmark] {failed} test(s) failed: {summary} ({date_str})"


def _find_duplicate_issue(title_prefix: str) -> int | None:
    """Check if an open issue with a similar title already exists."""
    result = _run(
        ["gh", "issue", "list", "--label", ISSUE_LABEL,
         "--state", "open", "--json", "number,title", "--limit", "50"],
        check=False,
    )
    if result.returncode != 0:
        return None
    try:
        issues = json.loads(result.stdout)
    except json.JSONDecodeError:
        return None
    for iss in issues:
        if iss.get("title", "").startswith(title_prefix):
            return iss["number"]
    return None


# ---------------------------------------------------------------------------
# Sub-command: benchmark
# ---------------------------------------------------------------------------

def cmd_benchmark() -> dict:
    """Run the benchmark suite and create a GitHub issue if any test fails."""
    logger.info("=== Running benchmarks ===")

    result = subprocess.run(
        [sys.executable, str(BENCHMARK_RUNNER), "--verbose"],
        capture_output=True,
        text=True,
        cwd=str(PROJECT_ROOT),
    )

    try:
        report = json.loads(result.stdout)
    except (json.JSONDecodeError, ValueError):
        logger.error("Failed to parse benchmark output as JSON")
        logger.error("stdout: %s", result.stdout[:500])
        logger.error("stderr: %s", result.stderr[:500])
        sys.exit(1)

    _save_benchmark_report(report)

    passed = report.get("passed", 0)
    failed = report.get("failed", 0)
    skipped = report.get("skipped", 0)
    logger.info("Results: %d passed, %d failed, %d skipped", passed, failed, skipped)

    if failed == 0:
        logger.info("All benchmarks passed. No issue needed.")
        return report

    if not _gh_available():
        logger.warning("gh CLI not available or not authenticated — skipping issue creation")
        return report

    title = _build_issue_title(report)
    dup = _find_duplicate_issue("[Benchmark]")
    if dup:
        logger.info("Open issue #%d already exists with [Benchmark] prefix — skipping creation", dup)
        return report

    body = _format_issue_body(report)
    try:
        _run([
            "gh", "issue", "create",
            "--title", title,
            "--body", body,
            "--label", f"{ISSUE_LABEL},{BENCHMARK_LABEL}",
        ])
        logger.info("Created issue: %s", title)
    except subprocess.CalledProcessError as e:
        logger.error("Failed to create issue: %s", e.stderr)

    return report


# ---------------------------------------------------------------------------
# Sub-command: fix
# ---------------------------------------------------------------------------

def _get_open_issues() -> list[dict]:
    result = _run(
        ["gh", "issue", "list",
         "--label", ISSUE_LABEL,
         "--state", "open",
         "--json", "number,title,body",
         "--limit", str(_config["max_issues"])],
        check=False,
    )
    if result.returncode != 0:
        logger.error("Failed to list issues: %s", result.stderr)
        return []
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError:
        logger.error("Invalid JSON from gh issue list")
        return []


def _branch_exists_remote(branch: str) -> bool:
    result = _run(
        ["git", "ls-remote", "--heads", "origin", branch],
        cwd=str(PROJECT_ROOT), check=False,
    )
    return bool(result.stdout.strip())


def _fix_issue(issue: dict) -> bool:
    """Attempt to fix a single issue using Claude in a git worktree. Returns True on success."""
    number = issue["number"]
    title = issue["title"]
    body = issue.get("body", "")
    branch = f"fix/issue-{number}"
    worktree_path = WORKTREES_DIR / branch.replace("/", "-")

    logger.info("--- Fixing issue #%d: %s ---", number, title)

    if _branch_exists_remote(branch):
        logger.info("Branch %s already exists on remote — skipping (PR may already exist)", branch)
        return False

    # Clean up stale worktree if present
    if worktree_path.exists():
        logger.info("Removing stale worktree at %s", worktree_path)
        _run(["git", "worktree", "remove", "--force", str(worktree_path)],
             cwd=str(PROJECT_ROOT), check=False)

    WORKTREES_DIR.mkdir(parents=True, exist_ok=True)

    try:
        _run(["git", "worktree", "add", str(worktree_path), "-b", branch],
             cwd=str(PROJECT_ROOT))
    except subprocess.CalledProcessError as e:
        logger.error("Failed to create worktree: %s", e.stderr)
        # Branch might exist locally; try checking it out instead
        try:
            _run(["git", "branch", "-D", branch], cwd=str(PROJECT_ROOT), check=False)
            _run(["git", "worktree", "add", str(worktree_path), "-b", branch],
                 cwd=str(PROJECT_ROOT))
        except subprocess.CalledProcessError:
            logger.error("Could not create worktree for branch %s", branch)
            return False

    prompt = textwrap.dedent(f"""\
        Read CLAUDE.md for project context.

        Fix GitHub Issue #{number}: {title}

        Issue body:
        {body}

        After fixing, run: python benchmarks/run_benchmarks.py --verbose
        to verify your changes resolve the issue.
        Commit all changes when done.
    """)

    logger.info("Launching Claude CLI in worktree %s", worktree_path)
    claude_result = _run(
        [
            "claude",
            "-p", prompt,
            "--allowedTools", "Read,Edit,Write,Bash",
            "--max-turns", str(CLAUDE_MAX_TURNS),
        ],
        cwd=str(worktree_path),
        check=False,
        capture=False,
    )

    if claude_result.returncode != 0:
        logger.warning("Claude exited with code %d for issue #%d", claude_result.returncode, number)

    # Stage, commit, and push
    _run(["git", "add", "-A"], cwd=str(worktree_path), check=False)

    diff_result = _run(["git", "diff", "--cached", "--quiet"],
                       cwd=str(worktree_path), check=False)
    if diff_result.returncode == 0:
        logger.warning("No changes after Claude run for issue #%d — skipping PR", number)
        _cleanup_worktree(worktree_path, branch)
        return False

    _run(
        ["git", "commit", "-m", f"fix: resolve issue #{number} — {title}"],
        cwd=str(worktree_path), check=False,
    )

    push_result = _run(
        ["git", "push", "-u", "origin", branch],
        cwd=str(worktree_path), check=False,
    )
    if push_result.returncode != 0:
        logger.error("Failed to push branch %s: %s", branch, push_result.stderr)
        _cleanup_worktree(worktree_path, branch)
        return False

    # Create PR
    pr_body = f"Closes #{number}\n\nAuto-generated fix by Claude Code via `scripts/orchestrator.py`."
    pr_result = _run(
        [
            "gh", "pr", "create",
            "--title", f"Fix #{number}: {title}",
            "--body", pr_body,
            "--head", branch,
        ],
        cwd=str(worktree_path), check=False,
    )
    if pr_result.returncode == 0:
        logger.info("PR created for issue #%d", number)
    else:
        logger.error("Failed to create PR: %s", pr_result.stderr)

    _cleanup_worktree(worktree_path, branch)
    return pr_result.returncode == 0


def _cleanup_worktree(worktree_path: Path, branch: str) -> None:
    _run(["git", "worktree", "remove", "--force", str(worktree_path)],
         cwd=str(PROJECT_ROOT), check=False)
    if worktree_path.exists():
        logger.warning("Worktree directory still exists, removing manually: %s", worktree_path)
        shutil.rmtree(worktree_path, ignore_errors=True)


def cmd_fix() -> None:
    """Find open issues labeled claude-fix and attempt to resolve them."""
    logger.info("=== Fixing open issues ===")

    if not _gh_available():
        logger.error("gh CLI not available or not authenticated — cannot list issues")
        sys.exit(1)

    if not _claude_available():
        logger.error("claude CLI not found in PATH — cannot fix issues")
        sys.exit(1)

    issues = _get_open_issues()
    if not issues:
        logger.info("No open issues with label '%s' — nothing to fix", ISSUE_LABEL)
        return

    logger.info("Found %d open issue(s) to process", len(issues))

    success_count = 0
    for issue in issues:
        try:
            ok = _fix_issue(issue)
            if ok:
                success_count += 1
        except Exception:
            logger.exception("Unexpected error fixing issue #%d", issue["number"])

    logger.info("Fix phase complete: %d/%d issues resulted in PRs", success_count, len(issues))


# ---------------------------------------------------------------------------
# Sub-command: loop
# ---------------------------------------------------------------------------

def cmd_loop() -> None:
    """Full cycle: run benchmarks then fix open issues."""
    logger.info("========== Orchestrator loop started ==========")
    start = datetime.now(timezone.utc)

    cmd_benchmark()
    cmd_fix()

    elapsed = (datetime.now(timezone.utc) - start).total_seconds()
    logger.info("========== Loop complete (%.0fs) ==========", elapsed)


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="CIDector orchestrator — benchmark, fix, and loop",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            sub-commands:
              benchmark   Run benchmark suite; create GitHub issue on failure
              fix         Pick up open claude-fix issues; fix with Claude CLI in worktrees
              loop        Full cycle: benchmark then fix
        """),
    )
    parser.add_argument(
        "command",
        choices=["benchmark", "fix", "loop"],
        help="Sub-command to run",
    )
    parser.add_argument(
        "--verbose", "-v", action="store_true",
        help="Increase log verbosity",
    )
    parser.add_argument(
        "--max-issues", type=int, default=_config["max_issues"],
        help=f"Max issues to process in one run (default: {_config['max_issues']})",
    )
    args = parser.parse_args()

    _config["max_issues"] = args.max_issues

    _setup_logging(args.verbose)

    dispatch = {
        "benchmark": cmd_benchmark,
        "fix": cmd_fix,
        "loop": cmd_loop,
    }
    dispatch[args.command]()


if __name__ == "__main__":
    main()
